debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,58 +11,61 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request_target' }}
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    env:
-      min-python-version: "3.10"
-
+  ok:
     steps:
-      - uses: actions/checkout@v4
+      - run: echo "ok"
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     min-python-version: "3.10"
 
-      - name: Set up Python ${{ env.min-python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ env.min-python-version }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -e .[dev]
+  #     - name: Set up Python ${{ env.min-python-version }}
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: ${{ env.min-python-version }}
 
-      - name: Lint with flake8
-        run: flake8
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install -e .[dev]
 
-      - name: Check black formatting
-        run: black . --check
-        if: success() || failure()
+  #     - name: Lint with flake8
+  #       run: flake8
 
-      - name: Check isort formatting
-        run: isort . --check
-        if: success() || failure()
+  #     - name: Check black formatting
+  #       run: black . --check
+  #       if: success() || failure()
 
-  build:
+  #     - name: Check isort formatting
+  #       run: isort . --check
+  #       if: success() || failure()
 
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
+  # build:
 
-    steps:
-      - uses: actions/checkout@v4
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.8", "3.9", "3.10", "3.11"]
 
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: List files
-        run: ls -al coml
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -e .[dev]
+  #     - name: List files
+  #       run: ls -al coml
 
-      - name: Test with pytest
-        run: |
-          pytest
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install -e .[dev]
+
+  #     - name: Test with pytest
+  #       run: |
+  #         pytest
